apiVersion: v1
kind: ConfigMap
metadata:
  name: kustomapp-configmap
  labels:
    app: kustomapp
data:
  index.html: |
    <html>
    <h1>Welcome</h1>
    </br>
    <h1 style="background-color:DodgerBlue;">Deployment</h1>
    <!-- <h1 style="background-color:DarkSeaGreen;">Deployment</h1> -->
    </html>