apiVersion: v1
kind: ConfigMap
metadata:
  name: kustomapp-configmap
  labels:
    app: kustomapp
data:
  index.html: |
    <html>
    <h1>Welcome</h1>
    </br>
    <h1 style="background-color:DogerBlue;">Blue Deployment</h1>
    </html>

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomapp
  labels:
    app: kustomapp
spec:
  selector:
    matchLabels:
      app: kustomapp
  replicas: 2
  template:
    metadata:
      labels:
        app: kustomapp
    spec:
      containers:
        - name: nginx
          image: nginx
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 80
          volumeMounts:
            - name: kustomapp-index-file
              mountPath: /usr/share/nginx/html/
      volumes:
      - name: kustomapp-index-file
        configMap:
          name: kustomapp-configmap
