apiVersion: v1
kind: Service
metadata:
  name: kustomapp-service
  labels:
    app: kustomapp
spec:
  type: NodePort
  selector:
    app: kustomapp
  ports:
  - nodePort: 31011
    protocol: TCP
    port: 80
    targetPort: 80