apiVersion: v1
kind: ConfigMap
metadata:
  name: kustomapp-configmap
  labels:
    app: kustomapp
data:
  index.html: |
    <html>
    <h1>Welcome</h1>
    </br>
    <h1 style="background-color:DogerBlue;">Blue Deployment</h1>
    </html