apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomapp
  labels:
    app: kustomapp
spec:
  selector:
    matchLabels:
      app: kustomapp
  namespace: argocd
  template:
    namespace: argocd