apiVersion: v1
kind: Service
metadata:
  name: kustomapp-dev-service
  labels:
    app: kustomapp
spec:
  type: NodePort
  namespace: developement
  selector:
    app: kustomapp
  ports:
  - nodePort: 31021
    protocol: TCP
    port: 80
    targetPort: 80