apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/instance: kustomapp
  name: kustomapp-1
spec:
  destination:
    namespace: development
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: argocd/kustomapp/base
    repoURL: 'https://github.com/jalsamir/common.git'
    targetRevision: HEAD