apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomapp-devlopment
spec:
  destination:
    namespace: development
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/kustomapp/environments/development
    repoURL: https://github.com/jalsamir/common.git
    targetRevision: HEAD