apiVersion: v1
kind: Service
metadata:
  name: ngapp-2-service
  labels:
    app: ngapp-2
spec:
  type: NodePort
  selector:
    app: ngapp-2
  ports:
  - nodePort: 30021
    protocol: TCP
    port: 80
    targetPort: 80