apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ngapp-1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: /ngapp/ngapp-1/
    repoURL: https://github.com/jalsamir/common.git
    targetRevision: HEAD