apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ngapp-1
  namespace: apps
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: app
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/ngapp/ngapp-1
    repoURL: https://github.com/jalsamir/common.git
    targetRevision: HEAD