apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ngapp-2
  namespace: applications
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  destination:
    namespace: applications
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/ngapp/ngapp-2
    repoURL: https://github.com/jalsamir/common.git
    targetRevision: HEAD