apiVersion: v1
kind: Service
metadata:
  name: ngapp-1-service
  labels:
    app: ngapp-1
spec:
  type: NodePort
  selector:
    app: ngapp-1
  ports:
  - nodePort: 30011
    protocol: TCP
    port: 80
    targetPort: 80