apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-configmap
  namespace: default
data:
  index.html: |
    <html>
    <h1>Welcome</h1>
    </br>
    <h1>Hi! This is a configmap Index file </h1>
    </html

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngapp-1
  labels:
    app: ngapp-1
spec:
  selector:
    matchLabels:
      app: ngapp-1
  replicas: 2
  template:
    metadata:
      labels:
        app: ngapp-1
    spec:
      containers:
        - name: nginx
          image: nginx
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-index-file
              mountPath: /usr/share/nginx/html/
          volumes:
            - name: nginx-index-file
              configMap:
                name: index-html-configmap
