apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngapp-1
  labels:
    app: ngapp-1
spec:
  selector:
    matchLabels:
      app: ngapp-1
  replicas: 2
  template:
    metadata:
      labels:
        app: ngapp-1
    spec:
      containers:
        - name: nginx
          image: nginx
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 80
